### ISSUE TITLE
AV Scan fails to run.

### ISSUE THREAD

**Issue by davepo** [davepo/AKA#1]
When running the 'aka.rb' standalone script, the Windows Defender AV scan fails to start.  The aka log references another log that contains a Policy/Feature disabled error. This occurs on a Windows 10 Home system that uses ESET as its main AV scanner.  I'm not sure what the issue is yet, or if it is unique to this system.

**Comment by wacert-dfir** [comment]
`MpCmdRun: Command Line: "C:\Program Files/Windows Defender/MpCmdRun.exe"  -Scan -ScanType 3 -File "F:/" -DisableRemediation 
 Start Time: ‎Fri ‎Jul ‎10 ‎2020 12:06:06

Starting RunCommandScan.
INFO: ScheduleJob is not set. Skipping signature update.
Scanning path as folder: F:/.
Start: MpScan(MP_FEATURE_SUPPORTED, dwOptions=33558577, path F:/, DisableRemediation = 1, BootSectorScan = 0, Timeout in days = 1)
ERROR: MpScanStart(dwOptions=33558577) Failed 800106BA
MpCmdRun: End Time: ‎Fri ‎Jul ‎10 ‎2020 12:06:06`

**Comment by davepo** [comment]
I replaced the defender command line scan with a custom ClamAV scan.  It seems to be working well so far.  Closing the issue.
